"""Generate the static graph-viewer data file from the schema.

Run as a module to (re)write ``site/data.js`` from ``schema/categories.yaml``::

    python -m cloud_architect.site

The viewer (``site/index.html``) loads ``site/data.js`` via a plain ``<script>``
tag, so the page works by double-clicking it — no server or build step needed.
``data.js`` is committed; regenerate it whenever the schema changes.
"""

from __future__ import annotations

import json
from pathlib import Path

from cloud_architect.schema import Schema, load_schema
from cloud_architect.validate import assert_valid

SITE_DIR = Path(__file__).resolve().parent.parent / "site"
DATA_FILE = SITE_DIR / "data.js"


def render_data(schema: Schema) -> str:
    """Return the JS source assigning the schema to ``window.GRAPH_DATA``."""
    payload = {
        "providers": schema.providers,
        "groups": schema.groups,
        "categories": [
            {
                "id": c.id,
                "group": c.group,
                "description": c.description,
                "terraformTypes": c.terraform_types,
                "deployAfter": c.deploy_after,
            }
            for c in schema.categories
        ],
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "// Generated by `python -m cloud_architect.site` — do not edit by hand.\n"
        f"window.GRAPH_DATA = {body};\n"
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: validate the schema and write ``site/data.js``."""
    schema = load_schema()
    assert_valid(schema)  # never publish an invalid schema to the viewer
    SITE_DIR.mkdir(exist_ok=True)
    DATA_FILE.write_text(render_data(schema), encoding="utf-8")
    edges = sum(len(c.deploy_after) for c in schema.categories)
    print(f"wrote {DATA_FILE} — {len(schema.categories)} categories, {edges} edges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
